# SITE INFORMATION
title: Your Name
tagline: Astronomer at Institution
baseurl: ""
paginate: 1
locale: "en"

# YOUR INFORMATION
# About/contact
author:
  name: Your Name
  headshot: img/headshot.png
  social:
    - type: email
      link: your.email@mail.com
    - type: github
      link: https://github.com/GitHub_Name
    - type: researchgate
      link: https://researchgate.net/profile/Profile_Name
    - type: twitter
      link: https://twitter.com/Twitter_Handle
    # Uncomment these to add more social icons to your site
    # - type: facebook
    #   link: https://facebook.com/StevenStetzler
    # - type: instagram
    #   link: https://instagram.com/stevenstetzler
    # - type: linkedin
    #   link: https://linkdin.com/stevenstetzler
    # - type: orcid
    #   link: https://orcid.org/id

# This adds the _pages folder to Jekyll and tells it to process and output those files
collections:
  pages:
    output: true
    permalink: /:path/

# NAVIGATION
# This determines which navigation buttons are shown on the website
# These MUST be the same as the title of the page (or the name of the file if that is not set)
nav:
  - home
  - about
  - research
  - publications

# Plugins
plugins:
  - jekyll-paginate

#Others
markdown: kramdown