
# SITE INFORMATION
title:        Site Title
tagline:      Site Tagline
baseurl:      "/github-pages-template"
paginate:     1
locale:       "en"

# YOUR INFORMATION
# Edit fields here to update the information and social icons displayed on the page
author:
  name: Your Name
  headshot: img/headshot.png
  social:
    - type: email
      link: your.email@mail.com
    - type: github
      link: https://github.com/Your_GitHub_Name
    - type: researchgate
      link: https://researchgate.net/profile/Profile_Name
#     - type: twitter
#       link: https://twitter.com/Twitter_Handle
    # Uncomment these to add more social icons to your site
    # - type: facebook
    #   link: https://facebook.com/...
    # - type: instagram
    #   link: https://instagram.com/...
    # - type: linkedin
    #   link: https://linkdin.com/...
    # - type: orcid
    #   link: https://orcid.org/id

# This adds the _pages folder to Jekyll and tells it to process and output those files
collections:
  pages:
    output: true
    permalink: /:path/
# When you add a new Markdown file in the _pages folder, it will be processed and outputted to the built site
# using the same directory structure that exists in _pages. For example the directory structure
#
# _pages
#   ├─── my-new-page.md
#   ├─── my-folder
#   |        my-second-page.md
#
# will create the following structure on your website
#
# http://<your_site_name>.com/my-new-page/index.html
# http://<your_site_name>.com/my-folder/my-second-page/index.html
#
# Note that when used as links /my-new-page/index.html is identical to /my-new-page/, so the following are valid as well:
# 
# http://<your_site_name>.com/my-new-page/
# http://<your_site_name>.com/my-folder/my-second-page/

# NAVIGATION
# This determines which navigation buttons are shown on the website
# Each button has a title (the text displayed in the button) and a link (the location that the button directs the user to)
nav:
  # The home page
  - title: Home
    link: ""
  # The about page, located in _pages/about.md
  - title: About
    link: /about/
  # A page about your research, located in _pages/research.md
  - title: Research
    link: /research/
  # A page to list your publications, located in _pages/publications.md
  - title: Publications
    link: /publications/
  # Note that you can alternatively link to your ADS search page like this:
    # link: https://ui.adsabs.harvard.edu/
  # A link to your CV, located at cv.pdf in the root directory
  - title: My CV
    link: /cv.pdf  

# Plugins
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
