# Setup
title:        Your Name
tagline:      Astronomer at Institution
baseurl:      "/github-pages-template/"
paginate:     1
locale:       "en"

# About/contact
author:
  name: Steven Stetzler
  headshot: img/headshot.png
  social:
    - type: email
      link: steven.stetzler@mail.com
    - type: github
      link: https://github.com/GitHub_Name
    - type: researchgate
      link: https://researchgate.net/profile/Profile_Name
    - type: twitter
      link: https://twitter.com/Twitter_Handle
    # Uncomment these to add more social icons to your site
    # - type: facebook
    #   link: https://facebook.com/StevenStetzler
    # - type: instagram
    #   link: https://instagram.com/stevenstetzler
    # - type: linkedin
    #   link: https://linkdin.com/stevenstetzler
    # - type: orcid
    #   link: https://orcid.org/id

# Plugins
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
